apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: cert-manager
spec:
  secretName: {{ .Values.certificate.name }}
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.certificate.dnsNames | quote }}