ingress:
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production

proxies:
  - name: ha
    ip: 192.168.107.10
    port: 8123
  - name: swnas01
    ip: 192.168.107.3
    port: 5001