email: stephenwolfe1@gmail.com

certificates:
  - name: star-swolfe-io
    dnsNames: "*.swolfe.io"
  - name: unifi-swolfe-io
    dnsNames: "unifi.swolfe.io"
    issuer: letsencrypt-production
  - name: nvr-swolfe-io
    dnsNames: "nvr.swolfe.io"
    issuer: letsencrypt-production